version: "3.5"
services:
  authentication-api:
    build: 
      args:
        - NODE_ENV=development
      context: ./authentication_api
    restart: always
    networks:
      - sawit-net
    environment:
      - NODE_ENV=development
    volumes:
      - ./authentication_api:/app/authentication_api
    ports:
      - "8000:8000"

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sawit-mysql:/var/lib/mysql'
      - './scripts/database.sql:/docker-entrypoint-initdb.d/1.sql'
    networks:
      - sawit-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

networks:
  sawit-net:
    driver: bridge

volumes:
  sawit-mysql:
    driver: local

